services:
  nginx:
    image: garud6209/retail-store-react:latest
    restart: unless-stopped
    ports:
      - "8081:80" # Serve React via Nginx
    networks:
      - retail_app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # Mount the custom Nginx config
    environment:
      - VITE_API_URL=http://15.207.109.188:8080 # Backend API URL for React app

  retail-store:
    image: garud6209/retail-store:latest
    container_name: retail-store
    ports:
      - "8080:8080" # Backend API
    networks:
      - retail_app
    environment:
      - SPRING_PROFILES_ACTIVE=ec2

networks:
  retail_app:
    driver: bridge
