services:
  nginx:
    image: garud6209/retail-store-react:latest
    container_name: nginx-react-app
    restart: unless-stopped
    ports:
      - "8081:80" # Serve React via Nginx
    networks:
      retail_app:
    environment:
      - REACT_APP_API_URL=${API_URL} # Dynamically set the API URL during startup
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  retail-store:
    image: garud6209/retail-store:latest
    container_name: retail-store
    ports:
      - "8080:8080" # Backend API
    networks:
      - retail_app
    environment:
      - SPRING_PROFILES_ACTIVE=ec2

networks:
  retail_app:
    driver: bridge
